### ISSUE TITLE
Embed Opencast Player instead of a video file

### ISSUE THREAD

**Issue by ebbertd** [unirz-tu-ilmenau/moodle-repository_opencast#1]
At the moment the previously uploaded video file is being embedded. However, that results in the loss of the Opencast Player features like zooming and changing the playback speed. Embedding the Opencast Player would increase the functionality.

**Comment by tobiasreischmann** [comment]
Priority would be to include the standard opencast player in moodle.
An option would be to use http://paellaplayer.upv.es/

**Comment by Dagefoerde** [comment]
fixed via https://github.com/learnweb/moodle-filter_opencastfilter
