### ISSUE TITLE
Link the uploaded videos

### ISSUE THREAD

**Issue by emmanueandales** [unirz-tu-ilmenau/moodle-repository_opencast#11]
Hi, I'm not sure what configuration to link my uploaded video's once you create another course. Can you please help me to achieve this objective. Right now, once you create another course and add a video by accessing insert media and pointing to the repo of opencast can't access the video's. see my image below for your reference.

Can you please provide any suggestion to fix this my concern

![screen shot 2018-09-25 at 10 38 12 am](https://user-images.githubusercontent.com/8894067/45990793-7555be80-c0b4-11e8-8bfe-b12b1ae9350b.png)

Looking forward to hear from you soon.

Cheers,
Emman

**Comment by tobiasreischmann** [comment]
Hey  Emman,
first, please bear in mind that this plugin is not yet released and has therefore to be considered as MATURITY_ALPHA or at least MATURITY_BETA. However, I will try to release the plugin soon and then it will be provided with a proper documentation.

For your case: The list of available videos is restricted to the videos associated with the opencast series, which is connected to you current course via the block_opencast. I assume that you either have not connected a series to a second course at all or that you are using a second empty series.
For future development, we decided to have one series per course, which is also relevant for access reasons. We are planning to provide backup/restore/import features to be able to copy videos to other courses in the future. 
In the meantime you can (if you want) reuse the same series in multiple courses. However, I would not recommend to do so.
Cheers,
Tobias
