### ISSUE TITLE
Repository not working on my moodle site

### ISSUE THREAD

**Issue by emmanueandales** [unirz-tu-ilmenau/moodle-repository_opencast#13]
Hi Tobias,

Can you please guide me on how to setup the updated plugin, i have already supplied the ID series and i can able to upload a video thru block-opencast.

See the image below of my setttings for repository.
![screen shot 2019-02-01 at 4 00 16 pm](https://user-images.githubusercontent.com/8894067/52110439-95d1ee80-263b-11e9-9908-e5b6b313805a.png)

Then my file picke which i can't see any video list for this course.
![screen shot 2019-02-01 at 4 05 01 pm](https://user-images.githubusercontent.com/8894067/52110496-c6198d00-263b-11e9-8b94-f5b83b4b9dbb.png)

BTW, im currently using the updated moodle instance 3.6.2v

Cheers,
Emman

**Comment by fishfree** [comment]
channel-id=api working for me.
